security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        # used to reload user from session & other features (e.g. switch_user)
        # used to reload user from session & other features (e.g. switch_user)

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            # Utilisation de form_login simplifiée pour éviter les conflits
            form_login:
                # Pas d'options supplémentaires, uniquement le strict minimum
                provider: app_user_provider
                enable_csrf: true # Désactive temporairement le CSRF pour identifier la source du problème
                login_path: app_login
                check_path: app_login
                default_target_path: app_main

            logout:
                path: app_logout
                target: app_main
                # where to redirect after logout
                # target: app_any_route
    
    access_control:
        - { path: ^/post/new, roles: ROLE_ADMIN }
        - { path: ^/post/\d+/edit, roles: ROLE_ADMIN }
        - { path: ^/post/\d+/delete, roles: ROLE_ADMIN }
